### ISSUE TITLE
User

### ISSUE THREAD

**Issue by DelukaDZ** [moengiant/DomoKodi#1]
Hello
Trying this script but getting a error inside KODI to check the log
This is what i get there

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'user' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/DomoKodi-master/default.py", line 533, in <module>
                                                Domoticz_direct( ip = hip, port = hport, username = huser, password = hpword, command = g_video_paused )
                                              File "/storage/.kodi/addons/DomoKodi-master/default.py", line 79, in Domoticz_direct
                                                url = 'http://%s:%s\@%s:%s/json.htm?type=command&param=switchscene&idx=%s&switchcmd=On' % (user,password,ip,port,command)
                                            NameError: global name 'user' is not defined
                                            -->End of Python script error report<--
I'm using version 6.0.3 of openelec

**Comment by moengiant** [comment]
I see the problem - 
I defined variables on line 68 as such

def Domoticz_direct( ip = hip, port = hport, username = huser, password = hpword, command = "" ):

There is no variable 'user' its actually 'username'. So on line 79 change 'user' to 'username' in the section that reads (user,password,ip,port,command).

Let me know if that fixes it and I'll update the code. 
Cheers

.
